#!/bin/bash
# Quick command reference for Stock S&R Scanner

echo "════════════════════════════════════════════════════════════════"
echo "  Stock Support & Resistance Scanner - Quick Commands"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📁 Location: /Users/sasi/stock_sr_scanner/"
echo ""
echo "🚀 QUICK COMMANDS:"
echo ""
echo "1. Run Demo Scanner (works offline)"
echo "   python demo_scanner.py"
echo ""
echo "2. Scan Real Stocks (requires internet)"
echo "   python stock_scanner.py"
echo ""
echo "3. Analyze NVDA (4H timeframe, 6 months)"
echo "   python example_usage.py"
echo ""
echo "4. Visualize Any Stock"
echo "   python visualize_scanner_results.py NVDA"
echo "   python visualize_scanner_results.py AAPL"
echo "   python visualize_scanner_results.py TSLA"
echo ""
echo "📚 DOCUMENTATION:"
echo ""
echo "   README.md              - Main project documentation"
echo "   QUICK_START.md         - Quick reference guide"
echo "   SCANNER_README.md      - Complete scanner guide"
echo "   SR_INDICATOR_README.md - Indicator details"
echo ""
echo "⚙️  SETUP:"
echo ""
echo "   pip install -r requirements.txt"
echo ""
echo "════════════════════════════════════════════════════════════════"
